---
apiVersion: v1
kind: Service
metadata:
  name: sitescope-backend
  namespace: sitescope
  labels:
    app: sitescope-backend
spec:
  type: ClusterIP
  selector:
    app: sitescope-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: sitescope-frontend
  namespace: sitescope
  labels:
    app: sitescope-frontend
spec:
  type: ClusterIP
  selector:
    app: sitescope-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
