---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sitescope-data
  namespace: sitescope
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
